env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
archives:
  -
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: osx
    format: zip
checksum:
  name_template: "checksums.txt"
